global using Crypto.Binance.Facades;
global using Crypto.Middleware;
global using Crypto.Runtime;
global using Crypto.RunTime;
global using Crypto.Utility;
global using System.Timers;
global using Topshelf;
global using Microsoft.Extensions.DependencyInjection;
//global using Crypto.Middleware.MassTransit.Rabbit;
global using Microsoft.Extensions.Logging;
global using Crypto.Binance;
global using Microsoft.Extensions.Configuration;global using Crypto.Logging;
global using Crypto.Console;
global using Crypto.MarketData;
global using Spectre.Console;
global using Crypto.Domain;
